version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://localhost:3000/
    volumes:
      - ../../repos:/repos
    ports:
      - "3000:3000"  # Web UI
      - "2222:22"    # SSH for Git
    restart: unless-stopped
